print('a is {}'.format('a'))
print('a is {} {} {}'.format(1, 2, 3))
print('a is {2} {1} {0}'.format(1, 2, 3))
print('a is {0} {1} {0}'.format(1, 2, 3))
print('My name is {name} {family}'.format(name='takuya', family='FAMILY'))